version: '3'

services:
  app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_started
  mongo:
    image: mongo